# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: device.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'device.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64\x65vice.proto\x12\x06\x64\x65vice\"\"\n\rDeviceRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\"\x9e\x01\n\nDeviceInfo\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12)\n\x06status\x18\x03 \x01(\x0e\x32\x19.device.DeviceInfo.Status\x12\x13\n\x0btemperature\x18\x04 \x01(\x01\"/\n\x06Status\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07STOPPED\x10\x01\x12\x0b\n\x07RUNNING\x10\x02\"1\n\x0cPowerRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x0e\n\x06\x65nable\x18\x02 \x01(\x08\"1\n\rPowerResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x80\x01\n\rDeviceService\x12\x36\n\tGetDevice\x12\x15.device.DeviceRequest\x1a\x12.device.DeviceInfo\x12\x37\n\x08SetPower\x12\x14.device.PowerRequest\x1a\x15.device.PowerResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'device_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DEVICEREQUEST']._serialized_start=24
  _globals['_DEVICEREQUEST']._serialized_end=58
  _globals['_DEVICEINFO']._serialized_start=61
  _globals['_DEVICEINFO']._serialized_end=219
  _globals['_DEVICEINFO_STATUS']._serialized_start=172
  _globals['_DEVICEINFO_STATUS']._serialized_end=219
  _globals['_POWERREQUEST']._serialized_start=221
  _globals['_POWERREQUEST']._serialized_end=270
  _globals['_POWERRESPONSE']._serialized_start=272
  _globals['_POWERRESPONSE']._serialized_end=321
  _globals['_DEVICESERVICE']._serialized_start=324
  _globals['_DEVICESERVICE']._serialized_end=452
# @@protoc_insertion_point(module_scope)
