"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class DeviceRequest(_message.Message):
    """请求设备信息"""

    DESCRIPTOR: _descriptor.Descriptor

    DEVICE_ID_FIELD_NUMBER: _builtins.int
    device_id: _builtins.str
    def __init__(
        self,
        *,
        device_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["device_id", b"device_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeviceRequest: _TypeAlias = DeviceRequest  # noqa: Y015

@_typing.final
class DeviceInfo(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _Status:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _StatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[DeviceInfo._Status.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        UNKNOWN: DeviceInfo._Status.ValueType  # 0
        STOPPED: DeviceInfo._Status.ValueType  # 1
        RUNNING: DeviceInfo._Status.ValueType  # 2

    class Status(_Status, metaclass=_StatusEnumTypeWrapper): ...
    UNKNOWN: DeviceInfo.Status.ValueType  # 0
    STOPPED: DeviceInfo.Status.ValueType  # 1
    RUNNING: DeviceInfo.Status.ValueType  # 2

    DEVICE_ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    TEMPERATURE_FIELD_NUMBER: _builtins.int
    device_id: _builtins.str
    name: _builtins.str
    status: Global___DeviceInfo.Status.ValueType
    temperature: _builtins.float
    def __init__(
        self,
        *,
        device_id: _builtins.str = ...,
        name: _builtins.str = ...,
        status: Global___DeviceInfo.Status.ValueType = ...,
        temperature: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["device_id", b"device_id", "name", b"name", "status", b"status", "temperature", b"temperature"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeviceInfo: _TypeAlias = DeviceInfo  # noqa: Y015

@_typing.final
class PowerRequest(_message.Message):
    """控制命令"""

    DESCRIPTOR: _descriptor.Descriptor

    DEVICE_ID_FIELD_NUMBER: _builtins.int
    ENABLE_FIELD_NUMBER: _builtins.int
    device_id: _builtins.str
    enable: _builtins.bool
    def __init__(
        self,
        *,
        device_id: _builtins.str = ...,
        enable: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["device_id", b"device_id", "enable", b"enable"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PowerRequest: _TypeAlias = PowerRequest  # noqa: Y015

@_typing.final
class PowerResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    message: _builtins.str
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
        message: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["message", b"message", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PowerResponse: _TypeAlias = PowerResponse  # noqa: Y015
