# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import device_pb2 as device__pb2


class DeviceServiceStub(object):
    """服务定义
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDevice = channel.unary_unary(
                '/device.DeviceService/GetDevice',
                request_serializer=device__pb2.DeviceRequest.SerializeToString,
                response_deserializer=device__pb2.DeviceInfo.FromString,
                )
        self.SetPower = channel.unary_unary(
                '/device.DeviceService/SetPower',
                request_serializer=device__pb2.PowerRequest.SerializeToString,
                response_deserializer=device__pb2.PowerResponse.FromString,
                )


class DeviceServiceServicer(object):
    """服务定义
    """

    def GetDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPower(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeviceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDevice,
                    request_deserializer=device__pb2.DeviceRequest.FromString,
                    response_serializer=device__pb2.DeviceInfo.SerializeToString,
            ),
            'SetPower': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPower,
                    request_deserializer=device__pb2.PowerRequest.FromString,
                    response_serializer=device__pb2.PowerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'device.DeviceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DeviceService(object):
    """服务定义
    """

    @staticmethod
    def GetDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/device.DeviceService/GetDevice',
            device__pb2.DeviceRequest.SerializeToString,
            device__pb2.DeviceInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetPower(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/device.DeviceService/SetPower',
            device__pb2.PowerRequest.SerializeToString,
            device__pb2.PowerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
